site_name: Silent Harmony KaW Wiki
site_description: A fan-made wiki for Kingdoms at War Epic Battles
site_author: Silent Harmony Clan

theme:
  name: material
  palette:
    - scheme: slate
      primary: indigo
      accent: teal

nav:
  - Home: index.md
  - Epic Battles:
      - Calydor the Depraved:
          - Warbeasts: epic-battles/tier1/warbeasts.md
          - Cover of Night: epic-battles/tier1/cover-of-night.md
          - Kingdom Assault: epic-battles/tier1/kingdom-assault.md
          - To the Chamber: epic-battles/tier1/to-the-chamber.md
          - The Depraved: epic-battles/tier1/the-depraved.md
          - Revenge of the Warbeasts (Premium): epic-battles/tier1/revenge-of-the-warbeasts.md
      - Z'uthmerak the Despair:
          - The Awakening: epic-battles/tier2/the-awakening.md
          - The Despair: epic-battles/tier2/the-despair.md
          - The Forgotten Ones: epic-battles/tier2/the-forgotten-ones.md
          - The Reckoning: epic-battles/tier2/the-reckoning.md
